"""orders update 26.02

Revision ID: 0874b540258e
Revises: 99975dc19b9f
Create Date: 2026-02-26 20:13:19.120714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0874b540258e'
down_revision: Union[str, Sequence[str], None] = '99975dc19b9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_status', postgresql.ENUM('unpaid', 'partial', 'paid', name='orderpaymentstatus'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
