"""change products and categories to real types

Revision ID: 41fe083d1fe1
Revises: b4a810889f34
Create Date: 2026-02-20 23:45:14.771038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "41fe083d1fe1"
down_revision: Union[str, Sequence[str], None] = "b4a810889f34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


productunit_enum = sa.Enum("piece", "kg", name="productunit")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # create enum type before adding a column that uses it
    bind = op.get_bind()
    productunit_enum.create(bind, checkfirst=True)

    op.create_table(
        "fillings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "name", name="uq_fillings_owner_name"),
    )
    op.create_index("ix_fillings_owner_id", "fillings", ["owner_id"], unique=False)

    op.create_table(
        "ingredients",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
        sa.Column("weight_grams", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner_id", "name", name="uq_ingredients_owner_name"),
    )
    op.create_index("ix_ingredients_owner_id", "ingredients", ["owner_id"], unique=False)

    op.create_table(
        "product_fillings",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("filling_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["filling_id"], ["fillings.id"]),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"]),
        sa.PrimaryKeyConstraint("product_id", "filling_id"),
    )

    op.create_table(
        "product_ingredients",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("ingredient_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["ingredient_id"], ["ingredients.id"]),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"]),
        sa.PrimaryKeyConstraint("product_id", "ingredient_id"),
    )

    op.create_table(
        "product_photos",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("uri", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_product_photos_product_id", "product_photos", ["product_id"], unique=False)

    op.add_column("products", sa.Column("recipe", sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=True))

    # if products already has rows, adding NOT NULL column without default will fail.
    # do it in 2 steps: add nullable, backfill, then set not null.
    op.add_column("products", sa.Column("unit", productunit_enum, nullable=True))
    op.execute("UPDATE products SET unit = 'piece' WHERE unit IS NULL")
    op.alter_column("products", "unit", nullable=False)

    op.drop_column("products", "description")
    op.drop_column("products", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column("products", sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column("products", sa.Column("description", sa.VARCHAR(length=2000), autoincrement=False, nullable=True))

    op.drop_column("products", "unit")
    op.drop_column("products", "recipe")

    op.drop_index("ix_product_photos_product_id", table_name="product_photos")
    op.drop_table("product_photos")
    op.drop_table("product_ingredients")
    op.drop_table("product_fillings")
    op.drop_index("ix_ingredients_owner_id", table_name="ingredients")
    op.drop_table("ingredients")
    op.drop_index("ix_fillings_owner_id", table_name="fillings")
    op.drop_table("fillings")

    # drop enum type after the column is gone
    bind = op.get_bind()
    productunit_enum.drop(bind, checkfirst=True)

    # ### end Alembic commands ###