"""orders add v5

Revision ID: 6f41fba94cbc
Revises: fc85ad68c05c
Create Date: 2026-02-21 16:28:39.325514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f41fba94cbc'
down_revision: Union[str, Sequence[str], None] = 'fc85ad68c05c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('client_name', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('client_phone', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('order_platform', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('delivery_type', sa.Enum('pickup', 'delivery', name='orderdeliverytype'), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=10000), nullable=True),
    sa.Column('decor_prices', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('references', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payment_status', sa.Enum('unpaid', 'partial', 'paid', name='orderpaymentstatus'), nullable=False),
    sa.Column('status', sa.Enum('new', 'inWork', 'ready', 'delivered', 'canceled', name='orderstatus'), nullable=False),
    sa.Column('paid_amount', sa.Integer(), nullable=False),
    sa.Column('in_planner', sa.Boolean(), nullable=False),
    sa.Column('total_price', sa.Integer(), nullable=False),
    sa.Column('last_payment_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_owner_id_created_at', 'orders', ['owner_id', 'created_at'], unique=False)
    op.create_index('ix_orders_owner_id_date', 'orders', ['owner_id', 'date'], unique=False)
    op.create_table('order_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('filling', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('unit', postgresql.ENUM('piece', 'kg', name='productunit', create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_lines_order_id', 'order_lines', ['order_id'], unique=False)
    op.create_index('ix_order_lines_product_id', 'order_lines', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_lines_product_id', table_name='order_lines')
    op.drop_index('ix_order_lines_order_id', table_name='order_lines')
    op.drop_table('order_lines')
    op.drop_index('ix_orders_owner_id_date', table_name='orders')
    op.drop_index('ix_orders_owner_id_created_at', table_name='orders')
    op.drop_table('orders')
    op.execute("DROP TYPE IF EXISTS orderstatus")
    op.execute("DROP TYPE IF EXISTS orderpaymentstatus")
    op.execute("DROP TYPE IF EXISTS orderdeliverytype")
    # ### end Alembic commands ###
