"""changed products/models v4

Revision ID: 8e563171e35c
Revises: 489a895bb239
Create Date: 2026-02-21 00:06:56.742275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8e563171e35c'
down_revision: Union[str, Sequence[str], None] = '489a895bb239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_product_fillings_filling_id', 'product_fillings', ['filling_id'], unique=False)
    op.create_index('ix_product_fillings_product_id', 'product_fillings', ['product_id'], unique=False)
    op.create_index('ix_product_ingredients_ingredient_id', 'product_ingredients', ['ingredient_id'], unique=False)
    op.create_index('ix_product_ingredients_product_id', 'product_ingredients', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_ingredients_product_id', table_name='product_ingredients')
    op.drop_index('ix_product_ingredients_ingredient_id', table_name='product_ingredients')
    op.drop_index('ix_product_fillings_product_id', table_name='product_fillings')
    op.drop_index('ix_product_fillings_filling_id', table_name='product_fillings')
    # ### end Alembic commands ###
