"""planner-tasks add

Revision ID: 9811279323a5
Revises: a66fd6b3c12e
Create Date: 2026-02-21 18:44:46.721662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9811279323a5'
down_revision: Union[str, Sequence[str], None] = 'a66fd6b3c12e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planner_tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_planner_tasks_owner_id_created_at', 'planner_tasks', ['owner_id', 'created_at'], unique=False)
    op.create_index('ix_planner_tasks_owner_id_date', 'planner_tasks', ['owner_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_planner_tasks_owner_id_date', table_name='planner_tasks')
    op.drop_index('ix_planner_tasks_owner_id_created_at', table_name='planner_tasks')
    op.drop_table('planner_tasks')
    # ### end Alembic commands ###
