"""change products.price type

Revision ID: b4a810889f34
Revises: e9077b542043
Create Date: 2026-02-20 23:11:59.392733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b4a810889f34'
down_revision: Union[str, Sequence[str], None] = 'e9077b542043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
