"""profile add

Revision ID: dbda2e81ca84
Revises: 9811279323a5
Create Date: 2026-02-24 13:49:45.016183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dbda2e81ca84'
down_revision: Union[str, Sequence[str], None] = '9811279323a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('profile_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('photo_uri', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', name='uq_profile_settings_owner_id')
    )
    op.create_index('ix_profile_settings_owner_id', 'profile_settings', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_profile_settings_owner_id', table_name='profile_settings')
    op.drop_table('profile_settings')
    # ### end Alembic commands ###
