"""email -> login

Revision ID: ebb9c8a93665
Revises: dbda2e81ca84
Create Date: 2026-02-24 18:22:54.162951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ebb9c8a93665'
down_revision: Union[str, Sequence[str], None] = 'dbda2e81ca84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1) добавляем login как nullable, чтобы пройти на непустой таблице
    op.add_column("users", sa.Column("login", sa.String(length=32), nullable=True))

    # 2) если уже есть пользователи, заполняем login из email безопасно (чтобы избежать коллизий)
    # login = часть до @ + "_" + первые 8 символов id
    op.execute(
        """
        UPDATE users
        SET login = left(split_part(email, '@', 1), 20) || '_' || left(id::text, 8)
        WHERE login IS NULL
        """
    )

    # 3) теперь можно сделать login обязательным
    op.alter_column("users", "login", nullable=False)

    # 4) email делаем необязательным
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(length=320),
        nullable=True,
    )

    # 5) уникальный индекс на login
    op.create_index(op.f("ix_users_login"), "users", ["login"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               nullable=False)
    op.drop_column('users', 'login')
    # ### end Alembic commands ###
